# Site settings
title: Moyhour Portfolio Website
email: ang.moyhour@outlook.com
url: http://mayleficent.github.io/moyhour_portfolio_website
description: "It is a simple website that I can show my skills and my work."
baseurl: "/moyhour_portfolio_website"


# Color settings (hex-codes without the leading hash-tag)

color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url: https://www.facebook.com/ang.moyhour
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
